/**
 * The icon rule: the directory's validator warns when a plugin has no icon, and this
 * checker says so too, under the source that says where the rule comes from.
 */

import test from 'node:test';
import assert from 'node:assert/strict';

import { checkGenerated, findingsFor, minimalPlugin, writeGeneratedFixture } from './helpers.mjs';

const ICON = '<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 256 256"><rect width="256" height="256" rx="48"/></svg>\n';

const manifestWith = (extra = {}) => JSON.stringify({
  name: 'generated-tools',
  version: '1.0.0',
  description: 'A plugin generated by the test suite.',
  author: { name: 'Example Author' },
  license: 'MIT',
  ...extra,
}, null, 2);

function iconFindings(name, files) {
  writeGeneratedFixture(name, { ...minimalPlugin(), ...files });
  const { json } = checkGenerated(name);
  return findingsFor(json, 'manifest/icon-missing');
}

test('a plugin with .claude-plugin/icon.svg has no icon finding', () => {
  assert.deepEqual(iconFindings('icon-file', { '.claude-plugin/icon.svg': ICON }), []);
});

test('a plugin with no icon gets a warning that names the validator as its source', () => {
  const hits = iconFindings('icon-absent', {});
  assert.equal(hits.length, 1, JSON.stringify(hits, null, 2));
  assert.equal(hits[0].result, 'warning');
  assert.equal(hits[0].source, 'validator');
  assert.equal(hits[0].sourceLabel, 'directory validator');
  assert.equal(hits[0].path, '.claude-plugin/icon.svg');
  assert.match(hits[0].fix, /icon\.svg \(square, at least 128 px\)/);
  assert.match(hits[0].fix, /publisher's avatar/);
});

test('an icon key in plugin.json counts as an icon', () => {
  const files = { '.claude-plugin/plugin.json': manifestWith({ icon: './assets/icon.svg' }) };
  assert.deepEqual(iconFindings('icon-key', files), []);
});

test('an empty or non-text icon key does not count', () => {
  for (const [label, icon] of [['empty', ''], ['blank', '   '], ['number', 3], ['object', {}]]) {
    const hits = iconFindings(`icon-key-${label}`, { '.claude-plugin/plugin.json': manifestWith({ icon }) });
    assert.equal(hits.length, 1, `${label}: ${JSON.stringify(hits, null, 2)}`);
  }
});

test('the icon warning does not stop a submission', () => {
  writeGeneratedFixture('icon-exit', { ...minimalPlugin() });
  const { json, status } = checkGenerated('icon-exit');
  assert.equal(status, 0, JSON.stringify(json?.findings, null, 2));
  assert.equal(json.summary.byResult.block, 0);
  assert.equal(json.summary.byResult.warning > 0, true, 'the missing icon is a warning');
});

test('a folder with no manifest is not asked for an icon', () => {
  const files = { ...minimalPlugin(), '.claude-plugin/plugin.json': null };
  delete files['.claude-plugin/plugin.json'];
  writeGeneratedFixture('icon-no-manifest', {
    ...files,
    'skills/demo/SKILL.md': '---\ndescription: A skill with no manifest around it.\n---\n\nHello.\n',
  });
  const { json } = checkGenerated('icon-no-manifest');
  assert.deepEqual(findingsFor(json, 'manifest/icon-missing'), []);
});
