#!/usr/bin/env node
/**
 * Print the rule catalogue as Markdown, for docs/rules.md.
 *
 * The catalogue is generated from the rules themselves, so it cannot drift from what the
 * checker does. Run it after changing a rule, and after moving the ruleset date:
 *
 *   node scripts/rules-doc.mjs > docs/rules.md
 */

import { RULES, JUDGMENT_ITEMS } from './rules/index.mjs';
import { RULESET, RESULTS, SOURCES, SECTIONS, RESULT_ORDER, TOOL_NAME, TOOL_VERSION } from './lib/registry.mjs';

function cell(text) {
  return String(text ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}

function build() {
  const lines = [
    '# The rules this checker applies',
    '',
    `Generated from the ruleset by node scripts/rules-doc.mjs. Do not edit by hand.`,
    '',
    `- Ruleset version: **${RULESET.version}**`,
    `- Mirrors: ${RULESET.source} (read ${RULESET.retrieved})`,
    `- Also drawn from: ${RULESET.alsoFrom.join(', ')}`,
    `- Rules: ${RULES.length}, plus ${JUDGMENT_ITEMS.length} decisions listed as out of reach`,
    '',
    'Each rule below carries the result class the directory would give the same problem, the',
    'title the portal uses in its report where the documentation gives one, and where the rule',
    'comes from. Only the first source is the directory\'s own checklist; a rule from any',
    'other source is this checker\'s reading of the documentation, and the directory does not',
    'check it in those words. Edit the rule in `scripts/rules/`, not this file.',
    '',
    '## Result classes',
    '',
    '| Class | What the portal does |',
    '| - | - |',
  ];
  for (const key of RESULT_ORDER) {
    lines.push(`| ${RESULTS[key].label} | ${cell(RESULTS[key].blurb)} |`);
  }
  lines.push('');
  lines.push('## Where a rule comes from', '');
  lines.push('| Source | Meaning | Rules |');
  lines.push('| - | - | - |');
  for (const [key, source] of Object.entries(SOURCES)) {
    lines.push(`| ${source.label} | ${cell(source.blurb)} | ${RULES.filter((rule) => rule.source === key).length} |`);
  }
  lines.push('');

  for (const [section, heading] of Object.entries(SECTIONS)) {
    const rules = RULES.filter((rule) => rule.section === section);
    if (rules.length === 0) continue;
    lines.push(`## ${heading}`, '');
    lines.push('| Rule | Result | Portal title | What it finds | How to fix it | Comes from |');
    lines.push('| - | - | - | - | - | - |');
    for (const rule of rules) {
      const heuristic = rule.heuristic ? ' (heuristic)' : '';
      lines.push(`| ${rule.id}${heuristic} | ${RESULTS[rule.result].label} | ${cell(rule.title ?? '—')} | ${cell(rule.what)} | ${cell(rule.fix ?? '—')} | ${SOURCES[rule.source].label} |`);
    }
    lines.push('');
  }

  lines.push('## What this checker cannot decide', '');
  lines.push('These are printed at the end of every report. A clean run does not settle them.', '');
  for (const item of JUDGMENT_ITEMS) {
    lines.push(`- **${cell(item.title)}** ${cell(item.detail)}`);
  }
  lines.push('');

  lines.push('## Known limits of these checks', '');
  lines.push(...LIMITS.map((limit) => `- ${cell(limit)}`));
  lines.push('');
  lines.push(`Generated by ${TOOL_NAME} ${TOOL_VERSION}.`);
  return `${lines.join('\n')}\n`;
}

/** The honest list of places where a local check is weaker than the real thing. */
const LIMITS = [
  'The default view reads the last commit, and `--worktree` reads the files on disk. Which one a report used is printed at the top of it.',
  'Rules tagged "this tool" are this checker\'s own advice. The directory does not check them.',
  'The `text`, `eol`, `ident` and `working-tree-encoding` attributes in a .gitattributes file may or may not be what the checklist means by "other attributes that rewrite file contents"; only `filter`, Git LFS included, is treated as a stop.',
  'The security scan runs on Anthropic\'s side and is not public. The rules in that section are heuristics that look for the categories the documentation names, and a clean result there is not a pass.',
  'The 50 MiB archive limit is estimated by deflating the tracked files in this process. The portal measures the archive GitHub builds, which this checker cannot fetch, so the number is close rather than exact.',
  'Launchers are read from the commands a plugin declares, the shell scripts it ships, the scripts a hook or an MCP server runs, and package.json scripts. Those are things the plugin runs, so those findings are confirmed. A launcher written in a code block of a SKILL.md, a command or an agent is an instruction rather than behaviour: it is reported as a heuristic, and it does not decide the exit code. A README and the reference files a skill keeps beside its SKILL.md are documentation and are not read at all.',
  'The credential rules know the shapes they know. A credential in an unusual format passes them, and a realistic example can be reported as one.',
  'The front matter reader checks the block as a whole and the `description` value in particular, because that is the value the table names. Other keys are read but not judged: `argument-hint: [system] [--source <path>]` is not valid YAML and is not reported as such.',
  'Whether a name is already listed, whether it resembles a brand, and what a reviewer decides about a held version are outside the files, and are listed in the report as such.',
  'The repository size and entry-count checks read the files Git tracks. In working-tree mode they read every file on disk that Git would not ignore.',
];

process.stdout.write(build());